### ISSUE TITLE
sidebar issue

### ISSUE THREAD

**Issue by Bounty38** [NYRI4/Comfy#161]
![image](https://github.com/user-attachments/assets/efe9e691-f315-4b82-8c3e-105cc65628d8)

appear next to sidebar instead of in it. Used to be fine, then broke after one of discord/vencord updates.

**Comment by pinetreemoonlight** [comment]
Same issue here, tried to fix with my noob skills but wasn't successful :( 

Additionally, the "own profile" button next to the chat bar is gone, and all that's left is a black square that isn't clickable (see pic)

![image](https://github.com/user-attachments/assets/b9c49115-32cc-4044-a3dd-10e333fd2914)

**Comment by Bounty38** [comment]
> Same issue here, tried to fix with my noob skills but wasn't successful :(
> 
> Additionally, the "own profile" button next to the chat bar is gone, and all that's left is a black square that isn't clickable (see pic)
> 

A guy named Jaden (discord 9.11.01) posted a temporary solution in Discord. You could modify theme file, or use a snippet in discord to apply that fix. 

```css
:root .panels_a4d4d9 > .container_b2ca13 > .avatarWrapper_b2ca13 {position: static;}
:root .panels_a4d4d9 > .container_b2ca13 > .avatarWrapper_b2ca13 > .avatar_b2ca13 {
    width: 32px !important;
    height: 32px !important;
}
:root .panels_a4d4d9 > .container_b2ca13 > .avatarWrapper_b2ca13 > .avatar_b2ca13 foreignObject {
    width: 32px !important;
    height: 32px !important;
}
:root .panels_a4d4d9 > .container_b2ca13 > .avatarWrapper_b2ca13 > .avatar_b2ca13 .pointerEvents_c51b4e {
    x:  22px;
    y: 22px;
}
:root section.panels_a4d4d9 > .container_b2ca13 { 
    height: 52px;
    justify-content: space-between;
}
:root section.panels_a4d4d9 > .container_b2ca13 > .flex_dc333f {
  position: static;
  flex-direction: row;
  width: unset;
  z-index: unset;
  background: transparent;
  padding: 0;
}
:root .panels_a4d4d9 > .container_b2ca13 > .avatarWrapper_b2ca13 > .avatar_b2ca13 + .nameTag_b2ca13 {display: block;max-width: 85px;}
:root section.panels_a4d4d9 > .container_b2ca13 > .flex_dc333f > .button_adca65 { margin: auto;}
:root nav.guilds_a4d4d9 .scroller-2TZvBN, :root nav.guilds_a4d4d9 .scroller_fea3ef { padding-bottom: 0;}
:root .chat_a7d72e .form_a7d72e { padding-left: 16px;}
:root .chat_a7d72e .form_a7d72e .channelTextArea_a7d72e .scrollableContainer_bdf0de::after, :root .chat_a7d72e .form_a7d72e .wrapper_faf5ab::after { content: none;}
```

This wouldnt solve the problem completely, as the bar would be only relocated to default place, but at least it wouldnt be a problem for now.

![image](https://github.com/user-attachments/assets/d4113f10-344d-4182-8729-7fb7313c00cd)

**Comment by pinetreemoonlight** [comment]
> A guy named Jaden (discord 9.11.01) posted a temporary solution in Discord. You could modify theme file, or use a snippet in discord to apply that fix.

Thank u so much for sharing, this is much better for now :)

**Comment by BergNetworks** [comment]
![v0LsXRpGer](https://github.com/user-attachments/assets/1170e338-6909-4f38-a176-56e01861b45b)

Same issue here.

**Comment by SuperSayf** [comment]
> A guy named Jaden (discord 9.11.01) posted a temporary solution in Discord. You could modify theme file, or use a snippet in discord to apply that fix.

Thanks, appreciated

**Comment by faustaahmad** [comment]
Idk how accurate this, feel free to modify
```css
:root {
  section[aria-label="User area"] > div[class*="container_"] {
    position: fixed;

    div[class*="avatarWrapper_"] {
      bottom: 27.5px;
      left: 256px;
    }
    div[class*="flex_"] {
      left: -72.5px;
      padding: 8 0 8 0;
    }
  }
  ul[data-list-id="guildsnav"] div[class^="footer_"] {
    display: none; /* comment this to make Discovery visible */
    bottom: 115px;
    padding: 8 0 8 0;
  }
  div[class*="unreadMentionsFixedFooter_"] {
    height: 16px;
    bottom: 128px; /* Discovery invisible
    bottom: 188px; /* Discovery visible */
  }
}

```
