### ISSUE TITLE
Animations causing high cpu usage

### ISSUE THREAD

**Issue by chargercat772** [NYRI4/Comfy#32]
how do i remove the flashing bubble above a server icon or channel? like not entirely, but remove the flash animation so i can reduce cpu usage.

**Comment by NYRI4** [comment]
```css
.listItem-GuPuDH.unread .wrapper-25eVIn::before, :root .wrapper-3Njo_c.unread:not(.expanded) .wrapper-25eVIn::before { animation: none !important;}
```
