### ISSUE TITLE
User settings text clips out of the screen

### ISSUE THREAD

**Issue by CZ75Delta** [NYRI4/Comfy#48]
This is a small issue, but the user settings text is cut by the edge of the screen like so:

![This is an image](https://i.imgur.com/fN4lybY.png)

**Comment by CZ75Delta** [comment]
If you're using Horizontal Server Bar you can use this to get the buttons top right where the text doesn't clip.

```css
.panels-3wFtMD > .container-YkUktl > .flex-2S1XBF {
    position: fixed !important;
    width: auto !important;
    top: 0 !important;
    left: auto !important;
    right: 0 !important;
    z-index: 1 !important;
    height: 55px !important;
    padding: 27px 0px 0px 0px !important;
    flex-direction: row !important;
}
```

Looks something like this:
![Preview](https://i.imgur.com/bTl3UJ7.png)
